language: go
go:
  - 1.x
notifications:
  email: always
env:
  - GO111MODULE=on
before_install:
  - go get golang.org/x/lint/golint
script:
  - make all
after_success:
  - bash <(curl -s https://codecov.io/bash)
