name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          make install

      - name: Vet
        run: |
          make vet

      - name: Build
        run: |
          make build
          docker build -t donny .

      - name: Test
        run: |
          make test
